query GetUserChallengeParticipationByUserId($userId: String!) {
  getUserChallengeParticipationByUserId(userId: $userId) {
    completionPercentage
    rank
    invitedChallengers
    participatingChallengers
    challenge {
      id
      name
      status
      startingDate
      endingDate
    }
  }
}

mutation CreateUserChallengeParticipation(
  $userId: String!
  $challengeId: String!
) {
  createUserChallengeParticipation(userId: $userId, challengeId: $challengeId) {
    id
    firstName
    lastName
    email
  }
}
