mutation CreateOrUpdateUserChallengeReaction(
  $content: ReactionEmojis!
  $challengeId: String!
) {
  createOrUpdateUserChallengeReaction(
    content: $content
    challengeId: $challengeId
  ) {
    id
    userId
    content
    challengeId
  }
}

query GetUserChallengesReactions($challengesId: [String!]!) {
  getUserChallengesReactions(challengesId: $challengesId) {
    challengeId
    content
  }
}

query GetUserChallengeReaction($challengeId: String!) {
  getUserChallengeReaction(challengeId: $challengeId) {
    content
  }
}

query GetReactionEmojis {
  getReactionEmojis {
    reactionEmoji
    icon
  }
}

mutation DeleteUserChallengeReaction($challengeId: String!) {
  deleteUserChallengeReaction(challengeId: $challengeId)
}

query GetChallengeReactions($challengeId: String!) {
  getChallengeReactions(challengeId: $challengeId) {
    id
    user {
      id
      firstName
      lastName
      email
    }
    userId
    content
    challengeId
  }
}
