mutation SignUp($userInputs: [UserInput!]!) {
  createUser(userInputs: $userInputs) {
    id
    firstName
    lastName
    email
  }
}

mutation SignIn($data: LoginInput!) {
  login(data: $data)
}

mutation DeleteUser($uuid: [String!]!) {
  deleteUser(uuid: $uuid)
}

mutation SignOut {
  logout
}
