query GetOwnNotifications {
  getOwnNotifications {
    id
    senderId
    receiverId
    date
    type
    content
    status
    hasBeenSeen
  }
}

mutation DeleteNotifications($deleteNotificationsId: [String!]!) {
  deleteNotifications(id: $deleteNotificationsId)
}

mutation UpdateNotification(
  $status: NotificationStatus
  $notificationId: String!
) {
  updateNotificationStatus(status: $status, notificationId: $notificationId) {
    id
    senderId
    receiverId
    date
    updatedDate
    type
    content
    status
    hasBeenSeen
  }
}
