mutation UpdateUserChallengeEcogesture(
  $ecogestureId: String!
  $challengeId: String!
  $proofUrl: String
) {
  updateUserChallengeEcogesture(
    ecogestureId: $ecogestureId
    challengeId: $challengeId
    proofUrl: $proofUrl
  ) {
    challengersScore {
      id
      score
    }
    userEcogestures {
      id
      challengeId
      userId
      ecogestureId
      proof
      completionDate
      reward
    }
  }
}
