query Challenges {
  challenges {
    id
    name
    status
    startingDate
    endingDate
  }
}

mutation CreateChallenges($challenges: [ChallengeCreationInput!]!) {
  createChallenges(challenges: $challenges) {
    id
    name
    status
    startingDate
    endingDate
  }
}

mutation UpdateChallenge(
  $data: ChallengeUpdateInput!
  $updateChallengeId: String!
) {
  updateChallenge(data: $data, id: $updateChallengeId) {
    id
    name
    status
    startingDate
    endingDate
  }
}

mutation DeleteChallenges($deleteChallengesId: [String!]!) {
  deleteChallenges(id: $deleteChallengesId)
}
