query GetFriends($status: String, $onlyFriends: Boolean) {
  getFriends(status: $status, onlyFriends: $onlyFriends) {
    friend {
      id
      firstName
      lastName
      email
    }
    status
  }
}

mutation UpdateFriendRelationship($friendId: String!) {
  updateFriendRelationship(friendId: $friendId) {
    id
    firstName
    lastName
    email
  }
}
