# This is a basic workflow to help you get started with Actions

name: deploy-staging

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["dev"]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-push-server:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build & push server
        uses: docker/build-push-action@v4
        with:
          push: true
          context: "{{defaultContext}}:server"
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/greenmates-server:staging
          file: "Dockerfile.production"
  build-and-push-client:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build & push client
        uses: docker/build-push-action@v4
        with:
          push: true
          context: "{{defaultContext}}:client"
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/greenmates-client:staging
          file: "Dockerfile.production"
  notify-vps:
    runs-on: ubuntu-latest
    needs:
      - build-and-push-client
      - build-and-push-server
    steps:
      - name: Trigger update production with webhook
        uses: wei/curl@master
        with:
          args: https://ops.neumann5.wns.wilders.dev/hooks/update-staging
